### ISSUE TITLE
Peeling sky model format

### ISSUE THREAD

**Issue by ajstewart** [ajstewart/rsmpp#19]
In the code, the different formatting is not accounted for correctly ('slofar_new' script). Needs a simple fix.

**Comment by ajstewart** [comment]
Ah looking at the code I see the problem. Whoever wrote it tried to account for the different sky model formatting but not correctly.

If you put a hash at the beginning of the format line it should then work:

#FORMAT = Name, Type, Ra, Dec, I, Q, U, V, ReferenceFrequency='60e6', SpectralIndex='[0.0]', MajorAxis, MinorAxis, Orientation

(I think that is allowed in BBS, it looks familiar)

**Original problem**

Successful readonly open of default-locked table L402114/L402114_SAP001_BAND00.MS.dppp/FIELD: 10 columns, 1 rows
Primary beam FWHM (est. deg) = 4.10361985239
RA = 207.424366667
Dec. = -4.45788055556

---

Successful readonly open of default-locked table L402114/L402114_SAP001_BAND01.MS.dppp/FIELD: 10 columns, 1 rows
Primary beam FWHM (est. deg) = 3.99440727717
RA = 207.424366667
Dec. = -4.45788055556

---

Traceback (most recent call last):
  File "/home/as24v07/bin/rsmpp/tools/peeling/peeling_new_slofarpp.py", line 87, in <module>
    ra_deg = float(ra_src[0])_15.0 + (float(ra_src[1])/60.0)_15.0 + (float(ra_src[2])/3600.0)_15.0
ValueError: could not convert string to float: Ra
Traceback (most recent call last):
  File "/home/as24v07/bin/rsmpp/tools/peeling/peeling_new_slofarpp.py", line 87, in <module>
    ra_deg = float(ra_src[0])_15.0 + (float(ra_src[1])/60.0)_15.0 + (float(ra_src[2])/3600.0)_15.0
ValueError: could not convert string to float: Ra
[01/11/2015 00:50:59] - INFO - Peeling L402114/L402114_SAP001_BAND00.MS.dppp...
[01/11/2015 00:50:59] - INFO - Peeling L402114/L402114_SAP001_BAND01.MS.dppp...
[01/11/2015 05:38:42] - INFO - Done!
[01/11/2015 05:38:42] - INFO - Post-bbs clipping process started on all sets...
[01/11/2015 05:38:44] - INFO - Performing post-BBS NDPPP flagging, with cut of 5000, on L402114_SAP001_BAND00.MS.dppp...
[01/11/2015 05:38:44] - INFO - Performing post-BBS NDPPP flagging, with cut of 5000, on L402114_SAP001_BAND01.MS.dppp...
[01/11/2015 05:39:09] - INFO - Done!
[01/11/2015 05:39:09] - INFO - Tidying up...
[01/11/2015 05:39:10] - INFO - All processed successfully!
[01/11/2015 05:39:10] - INFO - Results can be found in LIGO_test_1
[01/11/2015 05:39:10] - INFO - Run finished at 01-Nov-2015 05:39:10 UTC with a runtime of 14:47:52.343901

skymodel is

FORMAT = Name, Type, Ra, Dec, I, Q, U, V, ReferenceFrequency='60e6', SpectralIndex='[0.0]', MajorAxis, MinorAxis, Orientation

# the next lines define the sources

Sun, GAUSSIAN, 13:50:12.3, -11.20.08.70,  35000, , , ,160e6, [2.0],  2000.0, 2000.0, 0.0
1319.9-0435, POINT, 13:19:55.21920000, -04.35.41.89200000, 1.1243, , , , , [-0.9563]
1320.0-0351, POINT, 13:20:05.32080000, -03.51.48.49200000, 1.45, , , , , [-0.7]
1320.4-0447, POINT, 13:20:28.33920000, -04.47.53.41200000, 1.5832, , , , , [-1.1269]
1321.1-0433, POINT, 13:21:06.98880000, -04.33.02.41200000, 1.2756, , , , , [-0.9279]
1321.2-0349, POINT, 13:21:15.54960000, -03.49.09.08400000, 0.9819, , , , , [-0.8012]
1321.2-0508, POINT, 13:21:16.74960000, -05.08.26.30400000, 1.1203, , , , , [-0.7864]
1321.5-0432, POINT, 13:21:35.10000000, -04.32.51.61200000, 1.0421, , , , , [-1.0279]
1321.6-0555, POINT, 13:21:38.20080000, -05.55.57.00000000, 1.0268, , , , , [-0.9576]
1321.6-0640, POINT, 13:21:39.60000000, -06.40.20.31600000, 1.1712, , , , , [-1.0994]
1321.7-0405, POINT, 13:21:42.47040000, -04.05.52.29600000, 1.5984, , , , , [-0.9488]
1321.9-0323, POINT, 13:21:57.50880000, -03.23.10.21200000, 1.5717, , , , , [-1.0921]
1321.9-0622, GAUSSIAN, 13:21:57.65040000, -06.22.56.78400000, 7.2993, , , , , [-0.9188], 33.4, 30.1, 119.1
1321.9-0600, POINT, 13:21:58.85040000, -06.00.12.09600000, 2.6286, , , , , [-0.9142]
1322.0-0159, POINT, 13:22:02.11920000, -01.59.03.58800000, 0.9823, , , , , [-0.9788]
1322.9-0322, GAUSSIAN, 13:22:58.27920000, -03.22.00.19200000, 1.64, , , , , [-0.7], 108.2, 62.4, 117.9
etc etc
